rootProject.name = "info_protection"
include("task_1")
include("task_2")
include("general")
include("task_3")
include("task_4")
include("task_5")
include("task_6")
include("task_7")
include("task_8")
